version: '1.1'
services:
  app:
    container_name: termii-visit-app-container
    image: termii-visit-app-image
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: termii-server
    image: postgres
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=visitDB